version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t_p4ssw0rd
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: m00dl3_p4ssw0rd
    networks:
      - moodle

  app:
    build: ./
    depends_on:
      - db
    volumes:
      - ./data/moodle/data/:/var/www/html/moodle_data
    ports:
      - "8000:80"
    restart: always
    networks:
      - moodle

networks:
  moodle: